services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Manila
      - TZ=Asia/Manila
    volumes:
      - ${HOME}/.n8n:/home/node/.n8n
      - ./exports:/home/node/exports
volumes:
  n8n_data:
